config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "about", to: "pages#about"

  resources :articles

  get "signup", to: "users#new"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  #ensures title field has a value
  validates :title, presence: true, length: { minimum: 6, maximum: 100 } 
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }  

  
end

app/models/user.rb
class User < ApplicationRecord
    # run this closure on the object before saving
    before_save { self.email = email.downcase }

    # one to many association with article
    # dependent articles will be destroyed if a user is destoryed
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
        uniqueness: { case_sensitive: false }, 
        length: { maximum: 105 },
        format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # get and return current user from session

    helper_method :current_user
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    # notice that logged_in calls the current_user method, which in turn either returns the current user or 
    # nil if there is no session[user_id] 
    helper_method :logged_in?
    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action."
            redirect_to login_path
        end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end

  def create
    # not needed to be so explicit
    #@article = Article.new(title: params[:article][:title], description: params[:article][:description])
    # instead rails can interpret what attributes are needed but needs to know what is allowed to be passed ("white listed")
    # NEED CODE TO TRAP FOR VALIDATION!
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      # flash helper for displaying a message
      flash[:notice] = "Article was created successfully."
      #  calls the show action - need to use @article rather than article_path to grab the new id of the object 
      redirect_to @article
    else
      # redraws the new action view
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      # flash helper for displaying a message
      flash[:notice] = "Article was updated successfully."
      #  calls the show action
      redirect_to article_path
    else
      # redraws the edit action view
      render 'edit'
    end
   end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private 

  def set_article
    if Article.exists?(params[:id])
      @article = Article.find(params[:id])
    else
      flash[:notice] = "Article not found."
      @articles = Article.all
      render 'index'
    end
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  # this assumes there is already a logged in user which is forced by prior before_action
  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You are not authorized for this action."
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
       redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "Bad email address or password."
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            # flash helper for displaying a message
            welcome = "Welcome, #{@user.username}, to Alpha Blog!" 
            flash[:notice] = welcome
            session[:user_id] = @user.id
            #  calls the show action - need to use @article rather than article_path to grab the new id of the object 
            redirect_to articles_path
        else
            # redraws the new action view
            render 'new'
        end      
    end

    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    def edit
    end

    def update
        if @user.update(user_params)
            # flash helper for displaying a message
            flash[:notice] = "Update successfull."
            #  calls the show action
            redirect_to user_path(@user)
        else
            # redraws the edit action view
            render 'edit'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles have been deleted. Bye :("
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You are not authorized for this action."
            redirect_to current_user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    # helper methods
    # this is to display an image associated with email address at gravatar website
    def gravatar_for(user, options = { size: 80 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block" )
    end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container" id="page-content">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, user_path(article.user) if article.user %>
          </div>
          <div class="card-body">
            <h5><%= link_to article.title, article_path(article), class: "card-title text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-success" %>
              <%= link_to 'Delete', article_path(article), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <% nonsense = @article %>
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
      <div class="mb-3 row justify-content-center">
        <%= link_to '[ Cancel and return ]', articles_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit this Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container" id="page-content">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
            <%= gravatar_for @article.user, size: 80 %>
          </div>
          <div class="card-body">
            <div class="card-text text-left ml-5"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-success" %>
              <%= link_to 'Delete', article_path(@article), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; - <%= link_to "Scoutbasketball.com", "https://scoutbasketball.com", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<!-- displays flash messages -->
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "View articles", articles_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"} %>
              </div>
            </li>
            <%= link_to "Log out", logout_path, class:"nav-link", method: :delete %>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", login_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", signup_path, class:"nav-link" %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>    
      <%= yield %>
    </div>
      <%= render 'layouts/footer' %>    
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About Page</h1>

<p>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>
</p>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
        <h1 class="display-4">Alpha Blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to 'Sign Up', signup_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<!-- check and display errors first -->
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from saving</h4>
        
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
 
    </div>
<% end %> 

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %> 
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter a valid email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter a password" %>
          </div>
        </div>

<div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
      <div class="mb-3 row justify-content-center">
        <%= link_to '[ Cancel and return ]', users_path, class: "text-info" %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit Your Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container" id="page-content">
<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
                <%= link_to gravatar_for(user, size: 100), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to 'View profile', user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
               <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-primary" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to 'Delete profile', user_path(user), class: "btn btn-outline-danger", 
                    method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago </small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>

<%= gravatar_for @user, size: 100 %>

<% if @user == current_user %>
  <div class="text-center mt-4">
      <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>    
  </div>
<% end %>
<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>